### ISSUE TITLE
callFunction generate wrong querie

### ISSUE THREAD

**Issue by Gagarin23** [diegomvh/ODataApiGen#15]
Hi, Diego!
After generate api from metadata I try call my custom method "GetProducts". For example:
![image](https://user-images.githubusercontent.com/59282770/157626576-31516ec9-6af1-4883-a9d5-7dd2349b5ae1.png)
The problem occurred in the final generated url. It was:
/Product/GetProduct
but not:
/Product/GetProducts()

**Comment by diegomvh** [comment]
Hi @Gagarin23
This parentheses issue is related to this other issue https://github.com/OData/AspNetCoreOData/issues/171
If you use OData 8 as backend, maybe you can set `EnableNonParenthesisForEmptyParameterFunction` to `true`
In the problem xuzhg [says](https://github.com/OData/AspNetCoreOData/issues/171#issuecomment-845579596) that in version 8 the expected behavior is:

**A route for an Edm function should have a parenthesis in the route template, even this function doesn't have parameters**

Perhaps it is good that the [library](https://github.com/diegomvh/angular-odata) supports both versions (7 and 8) through some option in the configuration.

Thank you for giving the library a try.

**Comment by diegomvh** [comment]
Hi @Gagarin23 
In the new version 0.100.0 of [angular-odata](https://github.com/diegomvh/angular-odata) the default behavior for functions is use parenthesis for empty parameters.
For backward compatibility are a new settings `nonParenthesisForEmptyParameterFunction`.

Many thanks for your issue report
