### ISSUE TITLE
Suggestion: Store the property names in the schema

### ISSUE THREAD

**Issue by kevindstanley1988** [diegomvh/ODataApiGen#4]
The schema file currently generates with the type,key and nullable. It would be a great addition to store the property name itself in the schema. 

**Example** - I have added the 'name' property to the schema
```
export const UserSchema = {
  UserId: {type: 'string', nullable:false, name: 'UserId'}
}
```

The benefit of having that stored would be for use cases with filter and select. Right now to select fields you have to use either the string, which isn't typed and is error prone or use a nameof function, which verifies the entered string is correct or not through the compiler. 

**Use cases** - From the odata client
current way - only way I can think of to get static typing with property names
```
    const nameofFactory = <T>(name: keyof T) => name;
    const service = this.leaguesService.entity(this.league.Id);
    service.expand({
      LeagueUsers: {
        select: [nameofFactory<LeagueUser>('IsLeagueAdmin')],
        expand: {
          User: {
            select: [nameofFactory<User>('FirstName'), nameofFactory('LastName')]
          }
        }
      }
```

If the schema had the property names stored in the generated ts file it could be used like this. The code is much cleaner and we don't need strings in our code to access property names.
```
    const service = this.leaguesService.entity(this.league.Id);
    service.expand({
      LeagueUsers: {
        select: [LeagueUserSchema.IsLeagueAdmin.name],
        expand: {
          User: {
            select: [UserSchema.FirstName.name, UserSchema.LastName.name]
          }
        }
      }
    }); 
```

I attempted to modify the generator code to do what I needed, but am having trouble getting the project to work out of the box. I cloned and attempted to build in visual studio, but cannot get anything working right. I do have it working straight from your docker script however, I just cannot build and use the source code.

**Comment by diegomvh** [comment]
Hi @kevindstanley1988,
For a while I was playing with this idea of ​​having a name attribute for the fields, thinking just how to improve the type check in the `expand`, `filter`, `select`, etc.
When I finally did not prosper anything on that side, I thought that the name field did not make much sense and I reserved it as a calculated value in the [object](https://github.com/diegomvh/angular-odata/blob/1221df2c255992fd4f6fe3caa13472dcd6abfec9/src/lib/models/schema.ts#L22) that is [built](https://github.com/diegomvh/angular-odata/blob/1221df2c255992fd4f6fe3caa13472dcd6abfec9/src/lib/models/schema.ts#L96) based on the definition of the scheme.

For type checking I thought about creating [types](https://github.com/diegomvh/angular-odata/blob/1221df2c255992fd4f6fe3caa13472dcd6abfec9/src/lib/resources/options.ts#L7) based on the definition of the instance (entity)
So that for example:

```typescript
export type Select<T> = keyof T | (keyof T)[];
export type OrderBy<T> = keyof T | keyof T[];
export type Filter<T> = string | PlainObject | Array<string | PlainObject>;
export type Expand<T> = string | ExpandQueryOptions<T> | Array<string | ExpandQueryOptions<T>>;
...
export interface ExpandQueryOptions<T> {
  select?: Select<T>;
  filter?: Filter<T>;
  orderBy?: OrderBy<T>;
  top?: number;
  expand?: Expand<any>;
}
...
```

You can provide static check for:

```typescript
interface Car {
  year: number;
}
interface Person {
  name: string;
  age: number;
  car: Car;
}
var a: Expand<Person> = {select: ["age"], expand: <Expand<Car>> {select: "year"}};
```
It is an idea that I did not finish developing because I went to play with the models, but maybe with a little feedback I can go to production soon.

Regards

PD: for now, if nothing comes out, maybe putting the name field in the definition is the most successful.
PD: Sorry for my poor English.

**Comment by diegomvh** [comment]
Create a (branch)[https://github.com/diegomvh/angular-odata/tree/types] to test type checking

**Comment by kevindstanley1988** [comment]
I think the Select/Expand/Filter/Orderby with generics is a fantastic way to handle this. 

It would be great to be able to handle this type checking through the actual service entities functions. For example when you go to do a .select on entities, type checking comes along for the ride.

```
const service = this.showService.entities();

// Name and Description get type checked based on the properties in the Schema that the ShowService handles
service.select(['Name', 'Description']); 
service.filter({Name: 'Kevin'});
```


PD: I would not have known you were non-native English speaker if you hadn't said anything

**Comment by diegomvh** [comment]
The new version 0.8.0 adds this feature.

The type check works for select, orderBy and expand ... I'm playing with Aggregate and the others but I don't try them with queries.

[code](https://github.com/diegomvh/angular-odata/blob/22835a635f601cd53fb53abc30c4b8fd41126f64/src/lib/resources/options.ts#L7)

It remains to be seen the use of the `name` field in the scheme.

**Comment by diegomvh** [comment]
Ready on v0.8
